// Code generated by proto/gen from proto/rpc.schema.json. DO NOT EDIT.
//
// Codable mirror of the hub /rpc contract. Everything lives in the HubRPC
// namespace. Properties are lowerCamelCase with CodingKeys mapping them to the
// snake_case wire names. Date-times are ISO-8601 strings; base64 fields are
// Data (JSONDecoder's default base64 strategy).

import Foundation

public enum HubRPC {
    public static let protocolVersion: Int = 1
    public static let minProtocolVersion: Int = 1

    /// Every method in x-methods (raw value = wire name).
    public enum Method: String, Codable, CaseIterable, Hashable, Sendable {
        case batteryList = "battery.list"
        case capabilitiesList = "capabilities.list"
        case clipboardAdd = "clipboard.add"
        case clipboardGet = "clipboard.get"
        case clipboardList = "clipboard.list"
        case configtmDiff = "configtm.diff"
        case configtmList = "configtm.list"
        case configtmRestore = "configtm.restore"
        case eventsPush = "events.push"
        case eventsWait = "events.wait"
        case handoffOffer = "handoff.offer"
        case homeState = "home.state"
        case hubDevices = "hub.devices"
        case hubPairCode = "hub.pair_code"
        case hubPoll = "hub.poll"
        case hubRegister = "hub.register"
        case hubReply = "hub.reply"
        case hubSend = "hub.send"
        case jobList = "job.list"
        case jobLogs = "job.logs"
        case macCamera = "mac.camera"
        case macLock = "mac.lock"
        case macScreen = "mac.screen"
        case macState = "mac.state"
        case notificationsClear = "notifications.clear"
        case notificationsDismiss = "notifications.dismiss"
        case notificationsList = "notifications.list"
        case peekShow = "peek.show"
        case peerCall = "peer.call"
        case peerList = "peer.list"
        case powerBoot = "power.boot"
        case powerState = "power.state"
        case powerWake = "power.wake"
        case sceneApply = "scene.apply"
        case scenePlan = "scene.plan"
        case sceneUndo = "scene.undo"
        case shelfGet = "shelf.get"
        case shelfList = "shelf.list"
        case shelfPut = "shelf.put"
        case shelfRemove = "shelf.remove"
        case status = "status"
        case transferBegin = "transfer.begin"
        case transferCancel = "transfer.cancel"
        case transferChunk = "transfer.chunk"
        case transferCommit = "transfer.commit"
        case transferStatus = "transfer.status"
        case zenApply = "zen.apply"
        case zenStatus = "zen.status"

        /// Module that owns the method.
        public var module: String {
            switch self {
            case .batteryList: return "battery"
            case .capabilitiesList: return "core"
            case .clipboardAdd: return "clipboard"
            case .clipboardGet: return "clipboard"
            case .clipboardList: return "clipboard"
            case .configtmDiff: return "configtm"
            case .configtmList: return "configtm"
            case .configtmRestore: return "configtm"
            case .eventsPush: return "core"
            case .eventsWait: return "core"
            case .handoffOffer: return "handoff"
            case .homeState: return "home"
            case .hubDevices: return "hub"
            case .hubPairCode: return "hub"
            case .hubPoll: return "hub"
            case .hubRegister: return "hub"
            case .hubReply: return "hub"
            case .hubSend: return "hub"
            case .jobList: return "job"
            case .jobLogs: return "job"
            case .macCamera: return "mac"
            case .macLock: return "mac"
            case .macScreen: return "mac"
            case .macState: return "mac"
            case .notificationsClear: return "notifications"
            case .notificationsDismiss: return "notifications"
            case .notificationsList: return "notifications"
            case .peekShow: return "peek"
            case .peerCall: return "peer"
            case .peerList: return "peer"
            case .powerBoot: return "power"
            case .powerState: return "power"
            case .powerWake: return "power"
            case .sceneApply: return "home"
            case .scenePlan: return "home"
            case .sceneUndo: return "home"
            case .shelfGet: return "shelf"
            case .shelfList: return "shelf"
            case .shelfPut: return "shelf"
            case .shelfRemove: return "shelf"
            case .status: return "core"
            case .transferBegin: return "transfer"
            case .transferCancel: return "transfer"
            case .transferChunk: return "transfer"
            case .transferCommit: return "transfer"
            case .transferStatus: return "transfer"
            case .zenApply: return "zen"
            case .zenStatus: return "zen"
            }
        }
    }

    /// Every event type in x-events (raw value = Event.type).
    public enum EventType: String, Codable, CaseIterable, Hashable, Sendable {
        case transferCompleted = "transfer.completed"
        case transferFailed = "transfer.failed"
        case transferProgress = "transfer.progress"
        case transferStarted = "transfer.started"

        /// Event.topic of this type (the topic to pass to events.wait).
        public var topic: String {
            switch self {
            case .transferCompleted: return "transfer"
            case .transferFailed: return "transfer"
            case .transferProgress: return "transfer"
            case .transferStarted: return "transfer"
            }
        }
    }

    /// device: the host's own battery. bluetooth: a peripheral connected to the host (Bluetooth, or a wireless receiver such as Logitech's).
    public enum BatteryKind: String, Codable, CaseIterable, Hashable, Sendable {
        case device = "device"
        case bluetooth = "bluetooth"
    }

    /// Default newest.
    public enum ClipboardListParamsOrder: String, Codable, CaseIterable, Hashable, Sendable {
        case newest = "newest"
        case oldest = "oldest"
    }

    /// Default include.
    public enum ClipboardListParamsProtected: String, Codable, CaseIterable, Hashable, Sendable {
        case include = "include"
        case exclude = "exclude"
        case only = "only"
    }

    public enum ClipboardType: String, Codable, CaseIterable, Hashable, Sendable {
        case text = "text"
        case image = "image"
        case files = "files"
    }

    /// Hyprland's verdict after this commit (hyprctl configerrors): unchecked when the commit didn't touch hypr/ or the check is off.
    public enum ConfigtmCheck: String, Codable, CaseIterable, Hashable, Sendable {
        case ok = "ok"
        case errors = "errors"
        case unchecked = "unchecked"
    }

    public enum DeviceKind: String, Codable, CaseIterable, Hashable, Sendable {
        case tower = "tower"
        case mac = "mac"
        case phone = "phone"
        case server = "server"
    }

    public enum DeviceOS: String, Codable, CaseIterable, Hashable, Sendable {
        case omarchy = "omarchy"
        case windows = "windows"
        case macos = "macos"
        case android = "android"
        case linux = "linux"
    }

    public enum ErrorCode: String, Codable, CaseIterable, Hashable, Sendable {
        case unauthorized = "unauthorized"
        case unknownMethod = "unknown_method"
        case invalidParams = "invalid_params"
        case moduleDisabled = "module_disabled"
        case notFound = "not_found"
        case tooLarge = "too_large"
        case unsupportedProtocol = "unsupported_protocol"
        case unavailable = "unavailable"
        case `internal` = "internal"
    }

    public enum HandoffOfferParamsKind: String, Codable, CaseIterable, Hashable, Sendable {
        case url = "url"
        case code = "code"
        case media = "media"
    }

    public enum HubDeviceKind: String, Codable, CaseIterable, Hashable, Sendable {
        case tower = "tower"
        case mac = "mac"
        case phone = "phone"
        case server = "server"
    }

    public enum JobListParamsTarget: String, Codable, CaseIterable, Hashable, Sendable {
        case tower = "tower"
        case server = "server"
    }

    public enum JobTarget: String, Codable, CaseIterable, Hashable, Sendable {
        case tower = "tower"
        case server = "server"
    }

    public enum MacCameraParamsMode: String, Codable, CaseIterable, Hashable, Sendable {
        case still = "still"
        case live = "live"
    }

    public enum MacStateResultState: String, Codable, CaseIterable, Hashable, Sendable {
        case locked = "locked"
        case unlocked = "unlocked"
        case asleep = "asleep"
        case unknown = "unknown"
    }

    public enum PowerBootParamsOS: String, Codable, CaseIterable, Hashable, Sendable {
        case omarchy = "omarchy"
        case windows = "windows"
    }

    public enum PowerState: String, Codable, CaseIterable, Hashable, Sendable {
        case off = "off"
        case windows = "windows"
        case locked = "locked"
        case nossh = "nossh"
        case omarchy = "omarchy"
        case suspended = "suspended"
        case unknown = "unknown"
    }

    public enum ShelfKind: String, Codable, CaseIterable, Hashable, Sendable {
        case file = "file"
        case text = "text"
        case link = "link"
    }

    public enum StatusResultRole: String, Codable, CaseIterable, Hashable, Sendable {
        case node = "node"
        case hub = "hub"
    }

    public enum TransferFailure: String, Codable, CaseIterable, Hashable, Sendable {
        case cancelled = "cancelled"
        case expired = "expired"
        case checksum = "checksum"
        case delivery = "delivery"
    }

    public enum TransferState: String, Codable, CaseIterable, Hashable, Sendable {
        case receiving = "receiving"
        case completed = "completed"
    }

    /// Where a committed transfer goes. Only the shelf so far.
    public enum TransferTarget: String, Codable, CaseIterable, Hashable, Sendable {
        case shelf = "shelf"
    }

    /// missing: in neither.
    public enum ZenFileState: String, Codable, CaseIterable, Hashable, Sendable {
        case inSync = "in_sync"
        case differs = "differs"
        case missingInProfile = "missing_in_profile"
        case missingInSource = "missing_in_source"
        case missing = "missing"
    }

    public struct ApprovedParams: Codable, Hashable, Sendable {
        /// Signed fingerprint-approval token from the phone.
        public var approval: String

        public init(approval: String) {
            self.approval = approval
        }
    }

    public struct Battery: Codable, Hashable, Sendable {
        public var asOf: String
        public var charging: Bool?
        /// Device id the battery belongs to or is connected to.
        public var host: String
        /// device: the host's own battery. bluetooth: a peripheral connected to the host (Bluetooth, or a wireless receiver such as Logitech's).
        public var kind: BatteryKind
        /// 0..100. Peripherals that only report coarse steps (low/normal/high/full) get UPower's mapping of that step. Devices that report no level at all are left out.
        public var level: Int64
        public var name: String

        public init(asOf: String, charging: Bool? = nil, host: String, kind: BatteryKind, level: Int64, name: String) {
            self.asOf = asOf
            self.charging = charging
            self.host = host
            self.kind = kind
            self.level = level
            self.name = name
        }

        enum CodingKeys: String, CodingKey {
            case asOf = "as_of"
            case charging
            case host
            case kind
            case level
            case name
        }
    }

    public struct BatteryListResult: Codable, Hashable, Sendable {
        public var batteries: [Battery]

        public init(batteries: [Battery]) {
            self.batteries = batteries
        }
    }

    public struct CapabilitiesListResult: Codable, Hashable, Sendable {
        public var capabilities: [Capability]

        public init(capabilities: [Capability]) {
            self.capabilities = capabilities
        }
    }

    public struct Capability: Codable, Hashable, Sendable {
        public var description: String
        public var device: String
        /// Answered by another local app (the notch, behind the Mac helper) instead of towerbridge itself; only other devices can call it here. Absent = false.
        public var forwarded: Bool?
        public var method: String
        public var module: String
        /// Requires a fingerprint approval on the phone.
        public var needsApproval: Bool
        public var preconditions: [String]?
        /// Typical time until the effect is ready.
        public var readySeconds: Int64?
        public var undoable: Bool

        public init(description: String, device: String, forwarded: Bool? = nil, method: String, module: String, needsApproval: Bool, preconditions: [String]? = nil, readySeconds: Int64? = nil, undoable: Bool) {
            self.description = description
            self.device = device
            self.forwarded = forwarded
            self.method = method
            self.module = module
            self.needsApproval = needsApproval
            self.preconditions = preconditions
            self.readySeconds = readySeconds
            self.undoable = undoable
        }

        enum CodingKeys: String, CodingKey {
            case description
            case device
            case forwarded
            case method
            case module
            case needsApproval = "needs_approval"
            case preconditions
            case readySeconds = "ready_seconds"
            case undoable
        }
    }

    /// Exactly one of text, image_base64 (any decodable image) or file_paths (non-empty, absolute) is used, checked in that order; none gives invalid_params. The notch validates these before checking whether clipboard history is on.
    public struct ClipboardAddParams: Codable, Hashable, Sendable {
        /// Caller name; the entry's source_app becomes "mcp.<client>" (empty or missing: mcp.agent). The hub sync-helper sends "hub" and skips mcp.hub entries.
        public var client: String?
        public var filePaths: [String]?
        public var imageBase64: Data?
        public var pin: Bool?
        public var text: String?

        public init(client: String? = nil, filePaths: [String]? = nil, imageBase64: Data? = nil, pin: Bool? = nil, text: String? = nil) {
            self.client = client
            self.filePaths = filePaths
            self.imageBase64 = imageBase64
            self.pin = pin
            self.text = text
        }

        enum CodingKeys: String, CodingKey {
            case client
            case filePaths = "file_paths"
            case imageBase64 = "image_base64"
            case pin
            case text
        }
    }

    /// One clipboard history entry (clipboard.list entries and the clipboard.add result). Extra fields by type: text: char_count, preview (not when protected). image: width, height. files: file_count, file_names (not when protected).
    public struct ClipboardEntry: Codable, Hashable, Sendable {
        public var charCount: Int64?
        public var fileCount: Int64?
        public var fileNames: [String]?
        public var height: Int64?
        public var id: String
        public var isPinned: Bool
        public var isProtected: Bool
        public var preview: String?
        /// Present only when protected, e.g. "Looks like a GitHub token".
        public var protectionReason: String?
        /// Bundle id / app id it was copied from; entries added through clipboard.add carry "mcp.<client>".
        public var sourceApp: String?
        public var timestamp: String
        public var type: ClipboardType
        public var width: Int64?

        public init(charCount: Int64? = nil, fileCount: Int64? = nil, fileNames: [String]? = nil, height: Int64? = nil, id: String, isPinned: Bool, isProtected: Bool, preview: String? = nil, protectionReason: String? = nil, sourceApp: String? = nil, timestamp: String, type: ClipboardType, width: Int64? = nil) {
            self.charCount = charCount
            self.fileCount = fileCount
            self.fileNames = fileNames
            self.height = height
            self.id = id
            self.isPinned = isPinned
            self.isProtected = isProtected
            self.preview = preview
            self.protectionReason = protectionReason
            self.sourceApp = sourceApp
            self.timestamp = timestamp
            self.type = type
            self.width = width
        }

        enum CodingKeys: String, CodingKey {
            case charCount = "char_count"
            case fileCount = "file_count"
            case fileNames = "file_names"
            case height
            case id
            case isPinned = "is_pinned"
            case isProtected = "is_protected"
            case preview
            case protectionReason = "protection_reason"
            case sourceApp = "source_app"
            case timestamp
            case type
            case width
        }
    }

    /// The ClipboardEntry fields without preview, plus one content field: text (text), paths (files), byte_size + image_png_base64 (image, always PNG), or content_withheld:true for protected entries.
    public struct ClipboardGetResult: Codable, Hashable, Sendable {
        public var byteSize: Int64?
        public var charCount: Int64?
        public var contentWithheld: Bool?
        public var fileCount: Int64?
        public var fileNames: [String]?
        public var height: Int64?
        public var id: String
        public var imagePngBase64: Data?
        public var isPinned: Bool
        public var isProtected: Bool
        /// Absolute paths; non-file URLs as absolute URL strings.
        public var paths: [String]?
        public var protectionReason: String?
        public var sourceApp: String?
        public var text: String?
        public var timestamp: String
        public var type: ClipboardType
        public var width: Int64?

        public init(byteSize: Int64? = nil, charCount: Int64? = nil, contentWithheld: Bool? = nil, fileCount: Int64? = nil, fileNames: [String]? = nil, height: Int64? = nil, id: String, imagePngBase64: Data? = nil, isPinned: Bool, isProtected: Bool, paths: [String]? = nil, protectionReason: String? = nil, sourceApp: String? = nil, text: String? = nil, timestamp: String, type: ClipboardType, width: Int64? = nil) {
            self.byteSize = byteSize
            self.charCount = charCount
            self.contentWithheld = contentWithheld
            self.fileCount = fileCount
            self.fileNames = fileNames
            self.height = height
            self.id = id
            self.imagePngBase64 = imagePngBase64
            self.isPinned = isPinned
            self.isProtected = isProtected
            self.paths = paths
            self.protectionReason = protectionReason
            self.sourceApp = sourceApp
            self.text = text
            self.timestamp = timestamp
            self.type = type
            self.width = width
        }

        enum CodingKeys: String, CodingKey {
            case byteSize = "byte_size"
            case charCount = "char_count"
            case contentWithheld = "content_withheld"
            case fileCount = "file_count"
            case fileNames = "file_names"
            case height
            case id
            case imagePngBase64 = "image_png_base64"
            case isPinned = "is_pinned"
            case isProtected = "is_protected"
            case paths
            case protectionReason = "protection_reason"
            case sourceApp = "source_app"
            case text
            case timestamp
            case type
            case width
        }
    }

    public struct ClipboardListParams: Codable, Hashable, Sendable {
        /// Clamped to 1..500, default 50.
        public var limit: Int64?
        /// At least 0, default 0.
        public var offset: Int64?
        /// Default newest.
        public var order: ClipboardListParamsOrder?
        public var pinnedOnly: Bool?
        /// Default include.
        public var protected: ClipboardListParamsProtected?
        /// Inclusive lower bound: RFC 3339 (with or without fraction), or a bare local yyyy-MM-ddTHH:mm:ss, yyyy-MM-ddTHH:mm, yyyy-MM-dd HH:mm or yyyy-MM-dd.
        public var since: String?
        /// Only this type (default: all).
        public var type: ClipboardType?
        /// Inclusive upper bound, same formats as since.
        public var until: String?

        public init(limit: Int64? = nil, offset: Int64? = nil, order: ClipboardListParamsOrder? = nil, pinnedOnly: Bool? = nil, protected: ClipboardListParamsProtected? = nil, since: String? = nil, type: ClipboardType? = nil, until: String? = nil) {
            self.limit = limit
            self.offset = offset
            self.order = order
            self.pinnedOnly = pinnedOnly
            self.protected = protected
            self.since = since
            self.type = type
            self.until = until
        }

        enum CodingKeys: String, CodingKey {
            case limit
            case offset
            case order
            case pinnedOnly = "pinned_only"
            case protected
            case since
            case type
            case until
        }
    }

    public struct ClipboardListResult: Codable, Hashable, Sendable {
        public var count: Int64
        public var entries: [ClipboardEntry]
        public var offset: Int64
        /// Matching entries before paging.
        public var total: Int64

        public init(count: Int64, entries: [ClipboardEntry], offset: Int64, total: Int64) {
            self.count = count
            self.entries = entries
            self.offset = offset
            self.total = total
        }
    }

    public struct ConfigtmCommit: Codable, Hashable, Sendable {
        public var check: ConfigtmCheck
        /// hyprctl configerrors output when check is errors.
        public var checkOutput: String?
        /// Changed paths, relative to the watched root (e.g. hypr/bindings.lua).
        public var files: [String]
        /// Full git commit hash.
        public var id: String
        public var message: String
        public var time: String

        public init(check: ConfigtmCheck, checkOutput: String? = nil, files: [String], id: String, message: String, time: String) {
            self.check = check
            self.checkOutput = checkOutput
            self.files = files
            self.id = id
            self.message = message
            self.time = time
        }

        enum CodingKeys: String, CodingKey {
            case check
            case checkOutput = "check_output"
            case files
            case id
            case message
            case time
        }
    }

    public struct ConfigtmDiffParams: Codable, Hashable, Sendable {
        public var id: String
        public var path: String?

        public init(id: String, path: String? = nil) {
            self.id = id
            self.path = path
        }
    }

    public struct ConfigtmDiffResult: Codable, Hashable, Sendable {
        public var id: String
        public var patch: String
        /// The patch was cut at 1 MiB.
        public var truncated: Bool

        public init(id: String, patch: String, truncated: Bool) {
            self.id = id
            self.patch = patch
            self.truncated = truncated
        }
    }

    public struct ConfigtmListParams: Codable, Hashable, Sendable {
        /// Default 50, max 500.
        public var limit: Int64?
        /// Only commits touching this path (relative to the watched root).
        public var path: String?

        public init(limit: Int64? = nil, path: String? = nil) {
            self.limit = limit
            self.path = path
        }
    }

    public struct ConfigtmListResult: Codable, Hashable, Sendable {
        public var commits: [ConfigtmCommit]
        public var count: Int64

        public init(commits: [ConfigtmCommit], count: Int64) {
            self.commits = commits
            self.count = count
        }
    }

    public struct ConfigtmRestoreParams: Codable, Hashable, Sendable {
        public var id: String
        public var path: String?

        public init(id: String, path: String? = nil) {
            self.id = id
            self.path = path
        }
    }

    public struct ConfigtmRestoreResult: Codable, Hashable, Sendable {
        public var files: [String]
        /// The new commit; empty when the folders already matched.
        public var id: String
        public var restoredFrom: String

        public init(files: [String], id: String, restoredFrom: String) {
            self.files = files
            self.id = id
            self.restoredFrom = restoredFrom
        }

        enum CodingKeys: String, CodingKey {
            case files
            case id
            case restoredFrom = "restored_from"
        }
    }

    public struct Device: Codable, Hashable, Sendable {
        /// Stable device id, e.g. tower, mac, phone, server. The tower keeps one id in both OSes.
        public var id: String
        public var kind: DeviceKind
        public var name: String
        public var os: DeviceOS

        public init(id: String, kind: DeviceKind, name: String, os: DeviceOS) {
            self.id = id
            self.kind = kind
            self.name = name
            self.os = os
        }
    }

    public struct Empty: Codable, Hashable, Sendable {
        public init() {
        }
    }

    public struct Event: Codable, Hashable, Sendable {
        /// Small ping payload only; content is fetched with the module's get method.
        public var data: [String: JSONValue]?
        /// Peer device id when the event was relayed from another device; empty for local events.
        public var origin: String?
        public var seq: Int64
        public var time: String
        /// Module name, e.g. shelf, clipboard, update.
        public var topic: String
        /// e.g. shelf.added, clipboard.added, update.available. Types listed in x-events have a typed data def there; others are documented by their module.
        public var type: String

        public init(data: [String: JSONValue]? = nil, origin: String? = nil, seq: Int64, time: String, topic: String, type: String) {
            self.data = data
            self.origin = origin
            self.seq = seq
            self.time = time
            self.topic = topic
            self.type = type
        }
    }

    public struct EventsPushParams: Codable, Hashable, Sendable {
        /// 1..64 events; data at most 4 KiB each.
        public var events: [PushedEvent]

        public init(events: [PushedEvent]) {
            self.events = events
        }
    }

    public struct EventsPushResult: Codable, Hashable, Sendable {
        public var published: Int64

        public init(published: Int64) {
            self.published = published
        }
    }

    public struct EventsWaitParams: Codable, Hashable, Sendable {
        /// Last seq seen; 0 for everything still buffered.
        public var cursor: Int64
        /// Max wait; server caps it (default 25000).
        public var timeoutMs: Int64?
        public var topics: [String]?

        public init(cursor: Int64, timeoutMs: Int64? = nil, topics: [String]? = nil) {
            self.cursor = cursor
            self.timeoutMs = timeoutMs
            self.topics = topics
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case timeoutMs = "timeout_ms"
            case topics
        }
    }

    public struct EventsWaitResult: Codable, Hashable, Sendable {
        public var cursor: Int64
        public var events: [Event]

        public init(cursor: Int64, events: [Event]) {
            self.cursor = cursor
            self.events = events
        }
    }

    public struct HandoffOfferParams: Codable, Hashable, Sendable {
        public var branch: String?
        public var file: String?
        public var kind: HandoffOfferParamsKind
        public var line: Int64?
        public var mediaItemId: String?
        /// Device id the offer comes from.
        public var origin: String
        public var positionMs: Int64?
        public var repo: String?
        public var title: String
        public var url: String?

        public init(branch: String? = nil, file: String? = nil, kind: HandoffOfferParamsKind, line: Int64? = nil, mediaItemId: String? = nil, origin: String, positionMs: Int64? = nil, repo: String? = nil, title: String, url: String? = nil) {
            self.branch = branch
            self.file = file
            self.kind = kind
            self.line = line
            self.mediaItemId = mediaItemId
            self.origin = origin
            self.positionMs = positionMs
            self.repo = repo
            self.title = title
            self.url = url
        }

        enum CodingKeys: String, CodingKey {
            case branch
            case file
            case kind
            case line
            case mediaItemId = "media_item_id"
            case origin
            case positionMs = "position_ms"
            case repo
            case title
            case url
        }
    }

    public struct HandoffOfferResult: Codable, Hashable, Sendable {
        public var accepted: Bool
        public var id: String?

        public init(accepted: Bool, id: String? = nil) {
            self.accepted = accepted
            self.id = id
        }
    }

    public struct HomeStateResult: Codable, Hashable, Sendable {
        public var devices: [StatusResult]
        /// Module-provided facts keyed by module.
        public var facts: [String: JSONValue]
        public var time: String

        public init(devices: [StatusResult], facts: [String: JSONValue], time: String) {
            self.devices = devices
            self.facts = facts
            self.time = time
        }
    }

    public struct HubDevice: Codable, Hashable, Sendable {
        public var id: String
        public var kind: HubDeviceKind
        public var lastSeen: String?
        public var name: String
        /// Polled the hub within the last 60 s.
        public var online: Bool
        public var os: String
        /// X25519 public key, base64 (std, padded).
        public var publicKey: String

        public init(id: String, kind: HubDeviceKind, lastSeen: String? = nil, name: String, online: Bool, os: String, publicKey: String) {
            self.id = id
            self.kind = kind
            self.lastSeen = lastSeen
            self.name = name
            self.online = online
            self.os = os
            self.publicKey = publicKey
        }

        enum CodingKeys: String, CodingKey {
            case id
            case kind
            case lastSeen = "last_seen"
            case name
            case online
            case os
            case publicKey = "public_key"
        }
    }

    public struct HubDevicesResult: Codable, Hashable, Sendable {
        public var devices: [HubDevice]

        public init(devices: [HubDevice]) {
            self.devices = devices
        }
    }

    /// A sealed call. box: base64(nonce(24) || NaCl box from the sender's key to the recipient's).
    public struct HubEnvelope: Codable, Hashable, Sendable {
        public var box: String
        public var from: String
        public var id: String

        public init(box: String, from: String, id: String) {
            self.box = box
            self.from = from
            self.id = id
        }
    }

    public struct HubPairCodeParams: Codable, Hashable, Sendable {
        /// Id the device will have, e.g. tower, mac, phone.
        public var deviceId: String

        public init(deviceId: String) {
            self.deviceId = deviceId
        }

        enum CodingKeys: String, CodingKey {
            case deviceId = "device_id"
        }
    }

    public struct HubPairCodeResult: Codable, Hashable, Sendable {
        public var code: String
        public var expires: String

        public init(code: String, expires: String) {
            self.code = code
            self.expires = expires
        }
    }

    public struct HubPollParams: Codable, Hashable, Sendable {
        /// Max wait; capped at 25000.
        public var timeoutMs: Int64?

        public init(timeoutMs: Int64? = nil) {
            self.timeoutMs = timeoutMs
        }

        enum CodingKeys: String, CodingKey {
            case timeoutMs = "timeout_ms"
        }
    }

    public struct HubPollResult: Codable, Hashable, Sendable {
        public var envelopes: [HubEnvelope]

        public init(envelopes: [HubEnvelope]) {
            self.envelopes = envelopes
        }
    }

    public struct HubRegisterParams: Codable, Hashable, Sendable {
        public var device: Device
        /// X25519 public key, base64.
        public var publicKey: String

        public init(device: Device, publicKey: String) {
            self.device = device
            self.publicKey = publicKey
        }

        enum CodingKeys: String, CodingKey {
            case device
            case publicKey = "public_key"
        }
    }

    public struct HubRegisterResult: Codable, Hashable, Sendable {
        public var deviceToken: String

        public init(deviceToken: String) {
            self.deviceToken = deviceToken
        }

        enum CodingKeys: String, CodingKey {
            case deviceToken = "device_token"
        }
    }

    public struct HubReplyParams: Codable, Hashable, Sendable {
        public var box: String
        public var id: String

        public init(box: String, id: String) {
            self.box = box
            self.id = id
        }
    }

    public struct HubReplyResult: Codable, Hashable, Sendable {
        /// false when the caller stopped waiting.
        public var delivered: Bool

        public init(delivered: Bool) {
            self.delivered = delivered
        }
    }

    public struct HubSendParams: Codable, Hashable, Sendable {
        public var box: String
        /// How long to wait for the reply; capped at 60000.
        public var timeoutMs: Int64?
        public var to: String

        public init(box: String, timeoutMs: Int64? = nil, to: String) {
            self.box = box
            self.timeoutMs = timeoutMs
            self.to = to
        }

        enum CodingKeys: String, CodingKey {
            case box
            case timeoutMs = "timeout_ms"
            case to
        }
    }

    public struct HubSendResult: Codable, Hashable, Sendable {
        /// The sealed reply, from the recipient's key to the sender's.
        public var box: String

        public init(box: String) {
            self.box = box
        }
    }

    public struct IdParams: Codable, Hashable, Sendable {
        public var id: String

        public init(id: String) {
            self.id = id
        }
    }

    public struct Job: Codable, Hashable, Sendable {
        public var exitCode: Int64?
        public var name: String
        public var running: Bool
        public var started: String?
        public var target: JobTarget

        public init(exitCode: Int64? = nil, name: String, running: Bool, started: String? = nil, target: JobTarget) {
            self.exitCode = exitCode
            self.name = name
            self.running = running
            self.started = started
            self.target = target
        }

        enum CodingKeys: String, CodingKey {
            case exitCode = "exit_code"
            case name
            case running
            case started
            case target
        }
    }

    public struct JobListParams: Codable, Hashable, Sendable {
        public var target: JobListParamsTarget?

        public init(target: JobListParamsTarget? = nil) {
            self.target = target
        }
    }

    public struct JobListResult: Codable, Hashable, Sendable {
        public var jobs: [Job]

        public init(jobs: [Job]) {
            self.jobs = jobs
        }
    }

    public struct JobLogsParams: Codable, Hashable, Sendable {
        public var name: String
        public var tail: Int64?

        public init(name: String, tail: Int64? = nil) {
            self.name = name
            self.tail = tail
        }
    }

    public struct JobLogsResult: Codable, Hashable, Sendable {
        public var lines: [String]

        public init(lines: [String]) {
            self.lines = lines
        }
    }

    public struct KnownIcon: Codable, Hashable, Sendable {
        public var app: String
        /// NotificationApp.icon_hash of the copy the caller holds.
        public var iconHash: String

        public init(app: String, iconHash: String) {
            self.app = app
            self.iconHash = iconHash
        }

        enum CodingKeys: String, CodingKey {
            case app
            case iconHash = "icon_hash"
        }
    }

    public struct MacCameraParams: Codable, Hashable, Sendable {
        public var approval: String
        public var mode: MacCameraParamsMode

        public init(approval: String, mode: MacCameraParamsMode) {
            self.approval = approval
            self.mode = mode
        }
    }

    public struct MacCameraResult: Codable, Hashable, Sendable {
        public var shelfItemId: String?
        public var url: String?

        public init(shelfItemId: String? = nil, url: String? = nil) {
            self.shelfItemId = shelfItemId
            self.url = url
        }

        enum CodingKeys: String, CodingKey {
            case shelfItemId = "shelf_item_id"
            case url
        }
    }

    public struct MacStateResult: Codable, Hashable, Sendable {
        public var state: MacStateResultState

        public init(state: MacStateResultState) {
            self.state = state
        }
    }

    public struct Notification: Codable, Hashable, Sendable {
        /// App id (Android package name).
        public var app: String
        public var appName: String
        /// Has an inline reply action (a later notifications.reply will use it).
        public var canReply: Bool
        /// Android category when set (msg, email, call, alarm, ...).
        public var category: String?
        /// Can be dismissed (ongoing ones can't).
        public var clearable: Bool
        /// Opaque id on the device (Android: StatusBarNotification key); pass it to notifications.dismiss.
        public var key: String
        /// Private content hidden by the owner's settings: title/text are the app's public version or empty.
        public var redacted: Bool
        /// Body (the expanded text when the app provides one), capped at 1000 characters.
        public var text: String?
        /// When it was posted.
        public var time: String
        public var title: String?

        public init(app: String, appName: String, canReply: Bool, category: String? = nil, clearable: Bool, key: String, redacted: Bool, text: String? = nil, time: String, title: String? = nil) {
            self.app = app
            self.appName = appName
            self.canReply = canReply
            self.category = category
            self.clearable = clearable
            self.key = key
            self.redacted = redacted
            self.text = text
            self.time = time
            self.title = title
        }

        enum CodingKeys: String, CodingKey {
            case app
            case appName = "app_name"
            case canReply = "can_reply"
            case category
            case clearable
            case key
            case redacted
            case text
            case time
            case title
        }
    }

    public struct NotificationApp: Codable, Hashable, Sendable {
        public var app: String
        /// Content hash of the icon PNG (first 16 hex digits of its SHA-256); present whenever the device has an icon for the app. Changes when the app's icon does.
        public var iconHash: String?
        /// App icon, PNG, at most 96 x 96. Left out when known_icons already has this icon_hash for the app.
        public var iconPngBase64: Data?
        public var name: String

        public init(app: String, iconHash: String? = nil, iconPngBase64: Data? = nil, name: String) {
            self.app = app
            self.iconHash = iconHash
            self.iconPngBase64 = iconPngBase64
            self.name = name
        }

        enum CodingKeys: String, CodingKey {
            case app
            case iconHash = "icon_hash"
            case iconPngBase64 = "icon_png_base64"
            case name
        }
    }

    public struct NotificationsClearResult: Codable, Hashable, Sendable {
        /// How many were dismissed.
        public var cleared: Int64

        public init(cleared: Int64) {
            self.cleared = cleared
        }
    }

    public struct NotificationsDismissParams: Codable, Hashable, Sendable {
        public var key: String

        public init(key: String) {
            self.key = key
        }
    }

    public struct NotificationsDismissResult: Codable, Hashable, Sendable {
        public var dismissed: Bool

        public init(dismissed: Bool) {
            self.dismissed = dismissed
        }
    }

    public struct NotificationsListParams: Codable, Hashable, Sendable {
        /// Only total and hidden, no notifications (a cheap badge refresh).
        public var countOnly: Bool?
        /// Also return apps[], each listed app's icon once (small PNG).
        public var icons: Bool?
        /// With icons: the icons the caller already has. An app whose current icon_hash matches comes back without icon_png_base64 (the caller keeps its copy); a changed or unknown one is sent. Omitted = send every icon, as before.
        public var knownIcons: [KnownIcon]?
        /// Default 50, max 200. total still counts all of them.
        public var limit: Int64?

        public init(countOnly: Bool? = nil, icons: Bool? = nil, knownIcons: [KnownIcon]? = nil, limit: Int64? = nil) {
            self.countOnly = countOnly
            self.icons = icons
            self.knownIcons = knownIcons
            self.limit = limit
        }

        enum CodingKeys: String, CodingKey {
            case countOnly = "count_only"
            case icons
            case knownIcons = "known_icons"
            case limit
        }
    }

    public struct NotificationsListResult: Codable, Hashable, Sendable {
        /// With icons: one entry per app in notifications.
        public var apps: [NotificationApp]?
        /// How many the owner's filters left out (secret, silent, ongoing, system).
        public var hidden: Int64
        public var notifications: [Notification]
        /// How many pass the filters (may exceed the list when limited).
        public var total: Int64

        public init(apps: [NotificationApp]? = nil, hidden: Int64, notifications: [Notification], total: Int64) {
            self.apps = apps
            self.hidden = hidden
            self.notifications = notifications
            self.total = total
        }
    }

    public struct PeekShowParams: Codable, Hashable, Sendable {
        public var body: String?
        public var durationMs: Int64?
        public var icon: String?
        /// 0..1, optional.
        public var progress: Double?
        public var source: String
        public var title: String

        public init(body: String? = nil, durationMs: Int64? = nil, icon: String? = nil, progress: Double? = nil, source: String, title: String) {
            self.body = body
            self.durationMs = durationMs
            self.icon = icon
            self.progress = progress
            self.source = source
            self.title = title
        }

        enum CodingKeys: String, CodingKey {
            case body
            case durationMs = "duration_ms"
            case icon
            case progress
            case source
            case title
        }
    }

    public struct PeekShowResult: Codable, Hashable, Sendable {
        public var rateLimited: Bool?
        public var shown: Bool

        public init(rateLimited: Bool? = nil, shown: Bool) {
            self.rateLimited = rateLimited
            self.shown = shown
        }

        enum CodingKeys: String, CodingKey {
            case rateLimited = "rate_limited"
            case shown
        }
    }

    public struct PeerCallParams: Codable, Hashable, Sendable {
        public var device: String
        public var method: String
        public var params: [String: JSONValue]?
        public var timeoutMs: Int64?

        public init(device: String, method: String, params: [String: JSONValue]? = nil, timeoutMs: Int64? = nil) {
            self.device = device
            self.method = method
            self.params = params
            self.timeoutMs = timeoutMs
        }

        enum CodingKeys: String, CodingKey {
            case device
            case method
            case params
            case timeoutMs = "timeout_ms"
        }
    }

    public struct PeerCallResult: Codable, Hashable, Sendable {
        /// The remote method's result.
        public var result: [String: JSONValue]

        public init(result: [String: JSONValue]) {
            self.result = result
        }
    }

    public struct PlanStep: Codable, Hashable, Sendable {
        public var at: String?
        public var device: String
        public var method: String
        public var params: [String: JSONValue]
        public var readySeconds: Int64?
        public var why: String?

        public init(at: String? = nil, device: String, method: String, params: [String: JSONValue], readySeconds: Int64? = nil, why: String? = nil) {
            self.at = at
            self.device = device
            self.method = method
            self.params = params
            self.readySeconds = readySeconds
            self.why = why
        }

        enum CodingKeys: String, CodingKey {
            case at
            case device
            case method
            case params
            case readySeconds = "ready_seconds"
            case why
        }
    }

    public struct PowerBootParams: Codable, Hashable, Sendable {
        public var os: PowerBootParamsOS

        public init(os: PowerBootParamsOS) {
            self.os = os
        }
    }

    public struct PowerBootResult: Codable, Hashable, Sendable {
        public var accepted: Bool
        public var etaSeconds: Int64?
        public var state: PowerState

        public init(accepted: Bool, etaSeconds: Int64? = nil, state: PowerState) {
            self.accepted = accepted
            self.etaSeconds = etaSeconds
            self.state = state
        }

        enum CodingKeys: String, CodingKey {
            case accepted
            case etaSeconds = "eta_seconds"
            case state
        }
    }

    public struct PowerStateResult: Codable, Hashable, Sendable {
        public var since: String?
        public var state: PowerState

        public init(since: String? = nil, state: PowerState) {
            self.since = since
            self.state = state
        }
    }

    /// An event handed over with events.push; the receiver assigns seq and keeps the rest.
    public struct PushedEvent: Codable, Hashable, Sendable {
        public var data: [String: JSONValue]?
        public var origin: String?
        /// When it happened at the source; default now.
        public var time: String?
        public var topic: String
        public var type: String

        public init(data: [String: JSONValue]? = nil, origin: String? = nil, time: String? = nil, topic: String, type: String) {
            self.data = data
            self.origin = origin
            self.time = time
            self.topic = topic
            self.type = type
        }
    }

    /// Body of POST /rpc, e.g. {"op":"shelf.list","args":{}}. Auth: header `Authorization: Bearer <token>`. Unknown top-level keys are ignored.
    public struct Request: Codable, Hashable, Sendable {
        /// Method params; optional, defaults to {}.
        public var args: [String: JSONValue]?
        /// Method name from x-methods.
        public var op: String
        /// Caller's protocol version. Optional; the notch ignores it, towerbridge answers unsupported_protocol below its min_protocol.
        public var `protocol`: Int64?

        public init(args: [String: JSONValue]? = nil, op: String, `protocol`: Int64? = nil) {
            self.args = args
            self.op = op
            self.protocol = `protocol`
        }
    }

    /// {"ok":true,"result":{...}} or {"ok":false,"error":"<message>","code":"<code>"}. The same shape is used for transport errors (401, 403, 404, 411, 413).
    public struct Response: Codable, Hashable, Sendable {
        /// Machine-readable error code (ok:false only). Optional: towerbridge always sends it, the notch does not yet; clients must cope without it (treat as internal, or infer from the HTTP status).
        public var code: ErrorCode?
        /// Human-readable message (ok:false only).
        public var error: String?
        public var ok: Bool
        public var result: [String: JSONValue]?

        public init(code: ErrorCode? = nil, error: String? = nil, ok: Bool, result: [String: JSONValue]? = nil) {
            self.code = code
            self.error = error
            self.ok = ok
            self.result = result
        }
    }

    public struct SceneApplyParams: Codable, Hashable, Sendable {
        public var planId: String

        public init(planId: String) {
            self.planId = planId
        }

        enum CodingKeys: String, CodingKey {
            case planId = "plan_id"
        }
    }

    public struct SceneApplyResult: Codable, Hashable, Sendable {
        public var applied: Bool
        public var sceneId: String

        public init(applied: Bool, sceneId: String) {
            self.applied = applied
            self.sceneId = sceneId
        }

        enum CodingKeys: String, CodingKey {
            case applied
            case sceneId = "scene_id"
        }
    }

    public struct ScenePlanParams: Codable, Hashable, Sendable {
        public var readyBy: String?
        public var scenario: String

        public init(readyBy: String? = nil, scenario: String) {
            self.readyBy = readyBy
            self.scenario = scenario
        }

        enum CodingKeys: String, CodingKey {
            case readyBy = "ready_by"
            case scenario
        }
    }

    public struct ScenePlanResult: Codable, Hashable, Sendable {
        public var planId: String
        public var steps: [PlanStep]
        public var unsupported: [String]

        public init(planId: String, steps: [PlanStep], unsupported: [String]) {
            self.planId = planId
            self.steps = steps
            self.unsupported = unsupported
        }

        enum CodingKeys: String, CodingKey {
            case planId = "plan_id"
            case steps
            case unsupported
        }
    }

    public struct SceneUndoParams: Codable, Hashable, Sendable {
        public var sceneId: String?

        public init(sceneId: String? = nil) {
            self.sceneId = sceneId
        }

        enum CodingKeys: String, CodingKey {
            case sceneId = "scene_id"
        }
    }

    public struct SceneUndoResult: Codable, Hashable, Sendable {
        public var undone: Bool

        public init(undone: Bool) {
            self.undone = undone
        }
    }

    /// Flat by kind: file: file_name, byte_size, data_base64 (a folder is zipped and file_name is the .zip name). text: text. link: url. No id or name.
    public struct ShelfGetResult: Codable, Hashable, Sendable {
        public var byteSize: Int64?
        public var dataBase64: Data?
        public var fileName: String?
        public var kind: ShelfKind
        public var text: String?
        public var url: String?

        public init(byteSize: Int64? = nil, dataBase64: Data? = nil, fileName: String? = nil, kind: ShelfKind, text: String? = nil, url: String? = nil) {
            self.byteSize = byteSize
            self.dataBase64 = dataBase64
            self.fileName = fileName
            self.kind = kind
            self.text = text
            self.url = url
        }

        enum CodingKeys: String, CodingKey {
            case byteSize = "byte_size"
            case dataBase64 = "data_base64"
            case fileName = "file_name"
            case kind
            case text
            case url
        }
    }

    /// One shelf item as shelf.list reports it. Extra fields by kind: file: file_name, path (non-temporary only), is_directory (folders only), byte_size; or missing:true with none of those. text: char_count, preview. link: url.
    public struct ShelfItem: Codable, Hashable, Sendable {
        public var byteSize: Int64?
        public var charCount: Int64?
        public var fileName: String?
        public var id: String
        public var isDirectory: Bool?
        /// Stored by the app itself (uploads); towerbridge deletes temporary items after a day.
        public var isTemporary: Bool
        public var kind: ShelfKind
        /// The file behind the item can no longer be found.
        public var missing: Bool?
        /// Display name: the file name, the trimmed text, or the URL without http(s)://.
        public var name: String
        /// Absolute path of the user's own file (non-temporary file items only).
        public var path: String?
        /// First 200 characters, followed by an ellipsis when cut.
        public var preview: String?
        public var url: String?

        public init(byteSize: Int64? = nil, charCount: Int64? = nil, fileName: String? = nil, id: String, isDirectory: Bool? = nil, isTemporary: Bool, kind: ShelfKind, missing: Bool? = nil, name: String, path: String? = nil, preview: String? = nil, url: String? = nil) {
            self.byteSize = byteSize
            self.charCount = charCount
            self.fileName = fileName
            self.id = id
            self.isDirectory = isDirectory
            self.isTemporary = isTemporary
            self.kind = kind
            self.missing = missing
            self.name = name
            self.path = path
            self.preview = preview
            self.url = url
        }

        enum CodingKeys: String, CodingKey {
            case byteSize = "byte_size"
            case charCount = "char_count"
            case fileName = "file_name"
            case id
            case isDirectory = "is_directory"
            case isTemporary = "is_temporary"
            case kind
            case missing
            case name
            case path
            case preview
            case url
        }
    }

    public struct ShelfListResult: Codable, Hashable, Sendable {
        public var count: Int64
        public var items: [ShelfItem]

        public init(count: Int64, items: [ShelfItem]) {
            self.count = count
            self.items = items
        }
    }

    /// Exactly one of text, url, or data_base64 (+ optional file_name) is used, checked in that order; none gives invalid_params. text must be non-empty; url must be absolute with a scheme and not file:. file_name is reduced to its last /-component and trimmed; empty, . or .. become "file". Uploaded files are always temporary.
    public struct ShelfPutParams: Codable, Hashable, Sendable {
        public var dataBase64: Data?
        public var fileName: String?
        /// Display name of the device the item comes from (e.g. "Le's S23"), for the receiver's UI (the notch's arrival peek says "from <from>"). Optional; towerbridge's peer module sets it on every shelf.put it forwards to the notch, from the caller's hub.devices entry. Not part of the dedupe key.
        public var from: String?
        /// Kind of that device for its icon: tower, mac, phone, server (Device.kind), or windows for the tower running Windows. Optional, set together with from.
        public var fromKind: String?
        public var text: String?
        public var url: String?

        public init(dataBase64: Data? = nil, fileName: String? = nil, from: String? = nil, fromKind: String? = nil, text: String? = nil, url: String? = nil) {
            self.dataBase64 = dataBase64
            self.fileName = fileName
            self.from = from
            self.fromKind = fromKind
            self.text = text
            self.url = url
        }

        enum CodingKeys: String, CodingKey {
            case dataBase64 = "data_base64"
            case fileName = "file_name"
            case from
            case fromKind = "from_kind"
            case text
            case url
        }
    }

    public struct ShelfPutResult: Codable, Hashable, Sendable {
        /// The shelf already held this content (towerbridge: same content hash; notch: same file path, URL or text); id and name are the existing item's.
        public var alreadyPresent: Bool
        public var id: String
        public var name: String

        public init(alreadyPresent: Bool, id: String, name: String) {
            self.alreadyPresent = alreadyPresent
            self.id = id
            self.name = name
        }

        enum CodingKeys: String, CodingKey {
            case alreadyPresent = "already_present"
            case id
            case name
        }
    }

    public struct ShelfRemoveResult: Codable, Hashable, Sendable {
        /// true if an item with that id existed and is now gone; false if there was none.
        public var removed: Bool

        public init(removed: Bool) {
            self.removed = removed
        }
    }

    /// The first eight fields are the notch's. The rest are optional additions: a peer without protocol is notch v1 speaking protocol 1, and its modules are core plus shelf/clipboard per shelf_enabled/clipboard_enabled. towerbridge always sends all of them.
    public struct StatusResult: Codable, Hashable, Sendable {
        /// App version (the notch's CFBundleShortVersionString; towerbridge's build version).
        public var appVersion: String
        public var autoProtectSecrets: Bool
        public var clipboardCount: Int64
        public var clipboardEnabled: Bool
        public var clipboardPinnedCount: Int64
        public var device: Device?
        /// Set when the forward target couldn't be asked for its status just now: forwarded modules are reported enabled and their counts (shelf_count, clipboard_count, clipboard_pinned_count) are unknown, sent as 0.
        public var forwardError: String?
        /// Methods other devices can call here that another local app answers (the Mac helper forwards them to the notch, D-128); their modules then count in shelf_enabled/clipboard_enabled and modules, with the forward target's values. Absent = nothing forwarded.
        public var forwarded: [String]?
        /// Cap on decoded payload bytes in either direction (67108864).
        public var maxPayloadBytes: Int64
        public var minProtocol: Int64?
        /// Enabled modules on this device.
        public var modules: [String]?
        public var `protocol`: Int64?
        public var role: StatusResultRole?
        public var shelfCount: Int64
        public var shelfEnabled: Bool
        public var time: String?

        public init(appVersion: String, autoProtectSecrets: Bool, clipboardCount: Int64, clipboardEnabled: Bool, clipboardPinnedCount: Int64, device: Device? = nil, forwardError: String? = nil, forwarded: [String]? = nil, maxPayloadBytes: Int64, minProtocol: Int64? = nil, modules: [String]? = nil, `protocol`: Int64? = nil, role: StatusResultRole? = nil, shelfCount: Int64, shelfEnabled: Bool, time: String? = nil) {
            self.appVersion = appVersion
            self.autoProtectSecrets = autoProtectSecrets
            self.clipboardCount = clipboardCount
            self.clipboardEnabled = clipboardEnabled
            self.clipboardPinnedCount = clipboardPinnedCount
            self.device = device
            self.forwardError = forwardError
            self.forwarded = forwarded
            self.maxPayloadBytes = maxPayloadBytes
            self.minProtocol = minProtocol
            self.modules = modules
            self.protocol = `protocol`
            self.role = role
            self.shelfCount = shelfCount
            self.shelfEnabled = shelfEnabled
            self.time = time
        }

        enum CodingKeys: String, CodingKey {
            case appVersion = "app_version"
            case autoProtectSecrets = "auto_protect_secrets"
            case clipboardCount = "clipboard_count"
            case clipboardEnabled = "clipboard_enabled"
            case clipboardPinnedCount = "clipboard_pinned_count"
            case device
            case forwardError = "forward_error"
            case forwarded
            case maxPayloadBytes = "max_payload_bytes"
            case minProtocol = "min_protocol"
            case modules
            case `protocol`
            case role
            case shelfCount = "shelf_count"
            case shelfEnabled = "shelf_enabled"
            case time
        }
    }

    public struct StreamResult: Codable, Hashable, Sendable {
        public var expires: String?
        public var url: String

        public init(expires: String? = nil, url: String) {
            self.expires = expires
            self.url = url
        }
    }

    /// Senders use transfer.* for every file when the target's status.modules has transfer; shelf.put stays for text, links, and files to targets without it (D-139). transfer_id is the sender's: 8-128 characters of A-Z a-z 0-9 . _ -, the same on every retry and resume (the file's sha256 hex is a good choice: a restarted sender resumes by itself). The receiver keys partials by sender and transfer_id. Beginning again with a different size or sha256 discards the old partial.
    public struct TransferBeginParams: Codable, Hashable, Sendable {
        /// Optional, for the receiver's UI.
        public var mime: String?
        /// File name, reduced to its last path component like shelf.put's file_name.
        public var name: String
        /// The whole file, lowercase hex (64).
        public var sha256: String
        /// Bytes, 0 allowed.
        public var size: Int64
        /// Default shelf.
        public var target: TransferTarget?
        public var transferId: String

        public init(mime: String? = nil, name: String, sha256: String, size: Int64, target: TransferTarget? = nil, transferId: String) {
            self.mime = mime
            self.name = name
            self.sha256 = sha256
            self.size = size
            self.target = target
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case mime
            case name
            case sha256
            case size
            case target
            case transferId = "transfer_id"
        }
    }

    public struct TransferBeginResult: Codable, Hashable, Sendable {
        /// ceil(size / chunk_size); 0 for an empty file (commit at once).
        public var chunkCount: Int64
        /// Bytes per chunk, decided by the receiver (towerbridge: 1048576). Use it, whatever the sender would prefer.
        public var chunkSize: Int64
        /// Set when this transfer was already committed: nothing to send, this is its item.
        public var completed: ShelfPutResult?
        /// The partial is deleted if no chunk arrives before then (each chunk extends it; towerbridge: 24 h).
        public var expires: String
        /// Chunks already stored (resume): send only the others.
        public var have: [TransferRange]
        public var receivedBytes: Int64
        public var transferId: String

        public init(chunkCount: Int64, chunkSize: Int64, completed: ShelfPutResult? = nil, expires: String, have: [TransferRange], receivedBytes: Int64, transferId: String) {
            self.chunkCount = chunkCount
            self.chunkSize = chunkSize
            self.completed = completed
            self.expires = expires
            self.have = have
            self.receivedBytes = receivedBytes
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case chunkCount = "chunk_count"
            case chunkSize = "chunk_size"
            case completed
            case expires
            case have
            case receivedBytes = "received_bytes"
            case transferId = "transfer_id"
        }
    }

    public struct TransferCancelResult: Codable, Hashable, Sendable {
        public var cancelled: Bool

        public init(cancelled: Bool) {
            self.cancelled = cancelled
        }
    }

    public struct TransferChunkParams: Codable, Hashable, Sendable {
        public var dataBase64: Data
        public var index: Int64
        /// This chunk's bytes, lowercase hex. A mismatch is invalid_params and the chunk is not stored (send it again).
        public var sha256: String
        public var transferId: String

        public init(dataBase64: Data, index: Int64, sha256: String, transferId: String) {
            self.dataBase64 = dataBase64
            self.index = index
            self.sha256 = sha256
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case dataBase64 = "data_base64"
            case index
            case sha256
            case transferId = "transfer_id"
        }
    }

    /// With several chunks in flight the answers can arrive out of order: show the largest received_bytes seen.
    public struct TransferChunkResult: Codable, Hashable, Sendable {
        /// Chunks still missing; 0 means commit.
        public var chunksLeft: Int64
        /// Bytes of this transfer the receiver has verified and stored, all chunks so far.
        public var receivedBytes: Int64
        public var size: Int64

        public init(chunksLeft: Int64, receivedBytes: Int64, size: Int64) {
            self.chunksLeft = chunksLeft
            self.receivedBytes = receivedBytes
            self.size = size
        }

        enum CodingKeys: String, CodingKey {
            case chunksLeft = "chunks_left"
            case receivedBytes = "received_bytes"
            case size
        }
    }

    public struct TransferCommitResult: Codable, Hashable, Sendable {
        /// The shelf item (already_present when the shelf held the same content).
        public var item: ShelfPutResult
        public var transferId: String

        public init(item: ShelfPutResult, transferId: String) {
            self.item = item
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case item
            case transferId = "transfer_id"
        }
    }

    /// Event.data of the transfer topic (x-events): every event carries transfer_id, name, size, from and received_bytes, so a UI that starts listening mid-transfer can draw from any of them. Published by the receiving device; on the Mac the helper also pushes them to the notch (events.push).
    public struct TransferEvent: Codable, Hashable, Sendable {
        /// transfer.failed.
        public var code: TransferFailure?
        /// Sender device id (empty: a local caller).
        public var from: String
        /// Sender's kind when known, as ShelfPutParams.from_kind (tower, mac, phone, server, windows).
        public var fromKind: String?
        /// Sender's display name when known (hub.devices); the same value a forwarded shelf.put carries as from.
        public var fromName: String?
        /// transfer.completed.
        public var item: ShelfPutResult?
        public var mime: String?
        public var name: String
        /// transfer.failed: what went wrong, in plain words.
        public var reason: String?
        public var receivedBytes: Int64
        /// transfer.started: chunks were already here.
        public var resumed: Bool?
        public var size: Int64
        /// transfer.progress: no chunk for 30 s.
        public var stalled: Bool?
        public var transferId: String

        public init(code: TransferFailure? = nil, from: String, fromKind: String? = nil, fromName: String? = nil, item: ShelfPutResult? = nil, mime: String? = nil, name: String, reason: String? = nil, receivedBytes: Int64, resumed: Bool? = nil, size: Int64, stalled: Bool? = nil, transferId: String) {
            self.code = code
            self.from = from
            self.fromKind = fromKind
            self.fromName = fromName
            self.item = item
            self.mime = mime
            self.name = name
            self.reason = reason
            self.receivedBytes = receivedBytes
            self.resumed = resumed
            self.size = size
            self.stalled = stalled
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case code
            case from
            case fromKind = "from_kind"
            case fromName = "from_name"
            case item
            case mime
            case name
            case reason
            case receivedBytes = "received_bytes"
            case resumed
            case size
            case stalled
            case transferId = "transfer_id"
        }
    }

    public struct TransferIdParams: Codable, Hashable, Sendable {
        public var transferId: String

        public init(transferId: String) {
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case transferId = "transfer_id"
        }
    }

    public struct TransferInfo: Codable, Hashable, Sendable {
        public var expires: String
        /// Sender device id; empty for a local caller.
        public var from: String
        /// completed only.
        public var item: ShelfPutResult?
        public var mime: String?
        public var name: String
        public var receivedBytes: Int64
        public var size: Int64
        public var state: TransferState
        public var transferId: String
        public var updated: String

        public init(expires: String, from: String, item: ShelfPutResult? = nil, mime: String? = nil, name: String, receivedBytes: Int64, size: Int64, state: TransferState, transferId: String, updated: String) {
            self.expires = expires
            self.from = from
            self.item = item
            self.mime = mime
            self.name = name
            self.receivedBytes = receivedBytes
            self.size = size
            self.state = state
            self.transferId = transferId
            self.updated = updated
        }

        enum CodingKeys: String, CodingKey {
            case expires
            case from
            case item
            case mime
            case name
            case receivedBytes = "received_bytes"
            case size
            case state
            case transferId = "transfer_id"
            case updated
        }
    }

    /// Chunk indices start..end-1.
    public struct TransferRange: Codable, Hashable, Sendable {
        public var end: Int64
        public var start: Int64

        public init(end: Int64, start: Int64) {
            self.end = end
            self.start = start
        }
    }

    public struct TransferStatusParams: Codable, Hashable, Sendable {
        /// Only this transfer (default: all).
        public var transferId: String?

        public init(transferId: String? = nil) {
            self.transferId = transferId
        }

        enum CodingKeys: String, CodingKey {
            case transferId = "transfer_id"
        }
    }

    public struct TransferStatusResult: Codable, Hashable, Sendable {
        public var transfers: [TransferInfo]

        public init(transfers: [TransferInfo]) {
            self.transfers = transfers
        }
    }

    public struct ZenApplyParams: Codable, Hashable, Sendable {
        /// Profile name or folder; default: the default profile.
        public var profile: String?

        public init(profile: String? = nil) {
            self.profile = profile
        }
    }

    public struct ZenApplyResult: Codable, Hashable, Sendable {
        /// Folder with the overwritten files; empty when nothing was overwritten.
        public var backup: String
        public var profile: String
        public var restartNeeded: Bool
        public var written: [String]

        public init(backup: String, profile: String, restartNeeded: Bool, written: [String]) {
            self.backup = backup
            self.profile = profile
            self.restartNeeded = restartNeeded
            self.written = written
        }

        enum CodingKeys: String, CodingKey {
            case backup
            case profile
            case restartNeeded = "restart_needed"
            case written
        }
    }

    public struct ZenManagedFile: Codable, Hashable, Sendable {
        /// user.js, chrome/userChrome.css or chrome/userContent.css.
        public var name: String
        public var state: ZenFileState

        public init(name: String, state: ZenFileState) {
            self.name = name
            self.state = state
        }
    }

    public struct ZenProfile: Codable, Hashable, Sendable {
        /// Folder name under the Zen root (profiles.ini Path).
        public var dir: String
        public var files: [ZenManagedFile]
        /// The default profile of this Zen install (installs.ini), else profiles.ini Default=1.
        public var isDefault: Bool
        /// Zen version that last opened the profile (compatibility.ini).
        public var lastVersion: String
        public var name: String
        public var normalTabsSync: Bool
        /// Signed in to a Mozilla account (Firefox Sync). The account itself is never reported.
        public var signedIn: Bool
        public var spacesSync: Bool

        public init(dir: String, files: [ZenManagedFile], isDefault: Bool, lastVersion: String, name: String, normalTabsSync: Bool, signedIn: Bool, spacesSync: Bool) {
            self.dir = dir
            self.files = files
            self.isDefault = isDefault
            self.lastVersion = lastVersion
            self.name = name
            self.normalTabsSync = normalTabsSync
            self.signedIn = signedIn
            self.spacesSync = spacesSync
        }

        enum CodingKeys: String, CodingKey {
            case dir
            case files
            case isDefault = "is_default"
            case lastVersion = "last_version"
            case name
            case normalTabsSync = "normal_tabs_sync"
            case signedIn = "signed_in"
            case spacesSync = "spaces_sync"
        }
    }

    public struct ZenStatusResult: Codable, Hashable, Sendable {
        /// A Zen profile root with profiles.ini exists.
        public var installed: Bool
        public var profiles: [ZenProfile]
        public var root: String
        /// Folder holding the shared user.js and chrome/ files.
        public var source: String
        /// The default profile's Zen is 1.22b or newer.
        public var spacesSyncSupported: Bool

        public init(installed: Bool, profiles: [ZenProfile], root: String, source: String, spacesSyncSupported: Bool) {
            self.installed = installed
            self.profiles = profiles
            self.root = root
            self.source = source
            self.spacesSyncSupported = spacesSyncSupported
        }

        enum CodingKeys: String, CodingKey {
            case installed
            case profiles
            case root
            case source
            case spacesSyncSupported = "spaces_sync_supported"
        }
    }

    /// Any JSON value, for free-form objects (Request.params, Event.data, ...).
    public enum JSONValue: Codable, Hashable, Sendable {
        case null
        case bool(Bool)
        case number(Double)
        case string(String)
        case array([JSONValue])
        case object([String: JSONValue])

        public init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if c.decodeNil() {
                self = .null
            } else if let v = try? c.decode(Bool.self) {
                self = .bool(v)
            } else if let v = try? c.decode(Double.self) {
                self = .number(v)
            } else if let v = try? c.decode(String.self) {
                self = .string(v)
            } else if let v = try? c.decode([JSONValue].self) {
                self = .array(v)
            } else {
                self = .object(try c.decode([String: JSONValue].self))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var c = encoder.singleValueContainer()
            switch self {
            case .null: try c.encodeNil()
            case .bool(let v): try c.encode(v)
            case .number(let v): try c.encode(v)
            case .string(let v): try c.encode(v)
            case .array(let v): try c.encode(v)
            case .object(let v): try c.encode(v)
            }
        }
    }
}
